### ISSUE TITLE
Remove RxJava 1 and 2 dependency.

### ISSUE THREAD

**Issue by magillus** [vicpinm/Kotlin-Realm-Extensions#14]
I think pushing for RxJava in the library is too much, making it not dependent on it and adding on extension for RxJava 1 and separate extension RxJava2 would be better
I already had issue where I needed to add because of dual versioning of RxJava usage
`
    packagingOptions { // because- com.github.vicpinm:krealmextensions
        exclude 'META-INF/rxjava.properties'
    }
`

**Comment by vicpinm** [comment]
Hi @magillus, I think you are right and I would like to separate these dependencies as library extensions. I hope to be able to change it soon. I will keep this issue opened to track this improvement.

**Comment by Dima-369** [comment]
We ran into the issue where the added RxJava dependency almost blew the app method count because the `io.reactivex` package adds about 10k methods (as reported by the dexcount-gradle-plugin).

Solved it by only using the `src/main/java/com/vicpin/krealmextensions/RealmExtensions.kt` file from this library because we do not rely on the other asynchronous methods.

Just noting in case anyone else stumbles upon the same issue :)

**Comment by vicpinm** [comment]
@magillus I have already separated the library into 3 modules. Now you have:

 compile "com.github.vicpinm:krealmextensions:1.1.5"
 compile 'com.github.vicpinm:krealmextensions-rxjava:1.1.5'
 compile 'com.github.vicpinm:krealmextensions-rxjava2:1.1.5'

I have used them in different projects and they are working fine. If you find any issue, please let me know.

**Comment by magillus** [comment]
thank you I think this issue can be marked as completed
