### ISSUE TITLE
Detached Realm objects

### ISSUE THREAD

**Issue by thebrokenbar** [vicpinm/Kotlin-Realm-Extensions#3]
Why queries return only detached objects? Isn't Realm so great because of data attached to it's reference?

Great work btw. 👍

**Comment by vicpinm** [comment]
Attached objets have an important constraint: they cannot be used through differens threads. So if you perform your queries on a background thread, results cannot be returned to de main thread in order to be used in your ui layer. Nevertheless, I will add a method like queryManaged(), in order to perform queries that return attached realm objects, in case anyone needs it.
