### ISSUE TITLE
Question about methods createOrUpdate() and save()

### ISSUE THREAD

**Issue by CyxouD** [vicpinm/Kotlin-Realm-Extensions#7]
May you explain difference between createOrUpdate() and save() methods? Are they equal?

**Comment by vicpinm** [comment]
Yes, the key diference is the primary key. CreateOrUpdate is only allowed for realm objects which have a primary key (this method calls to copyToRealmOrUpdate from realm api, which requires that). Save method is preferable because it checks for you if your object has or not a primary key. If your object has a primary key, and there is another object in your db with se same primary key, this method will update your object. But if your object doesn't have a primary key, or it has one but that key doesn't exists in your db, it will create a new entry. I recommend you to use always save method instead of createOrUpdate.
